apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
        - name: mycontainer
          image: nashit836/nginx:latest
          ports:
            - containerPort: 80
